project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - text: home
        href: index.qmd
      - text: Pipelines
        href: pipelines.qmd
      - text: Data Preparation
        href: data-prep.qmd
      - text: Data Pins
        href: data-pins.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute: 
  freeze: true