---
format: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# tidymodels-pipelines

<!-- badges: start -->
<!-- badges: end -->

## How to build site locally.

All examples on this website uses CRAN version of R packages, and they should be installed as such.

### Docker

Installing Docker should be fairly straightforward. Please refer to [Get Started](https://www.docker.com/get-started/) for how to.

### Setting up Posit Connect

{{< include _include-envvar-connect.qmd >}}

### Setting up Amazon S3

For the smoothest experience, we recommend that you authenticate using environment variables. The two variables you will need are `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.

::: {.callout-warning}
Depending on your S3 setup, you will need to use additional variables to connect. Please see <https://github.com/paws-r/paws/blob/main/docs/credentials.md> and this [pins issue](https://github.com/rstudio/pins-r/issues/608) for help if the following paragraphs doesn't work for you.
:::

::: {.callout-tip}
The function [usethis::edit_r_environ()](https://usethis.r-lib.org/reference/edit.html) can be very handy to open `.Renviron` file to specify your environment variables.
:::

You can find both of these keys in the same location. 

1. Open the [AWS Console](https://console.aws.amazon.com/)
1. Click on your username near the top right and select `Security Credentials`
1. Click on `Users` in the sidebar
1. Click on your username
1. Click on the `Security Credentials` tab
1. Click `Create Access Key`
1. Click `Show User Security Credentials`

Once you have those two, you can add them to your `.Renviron` file in the following format:

```markdown
AWS_SECRET_ACCESS_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxxx
AWS_ACCESS_KEY_ID=xxxxxxxxxxxxxxxxxxxxxxxxxxxx
```
