# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)
b <- board_s3(bucket = "tidymodels-pipeline-example", region = structure("us-west-1", tags = list(type = "scalar")))
v <- vetiver_pin_read(b, "flights_xgb", version = "20240316T013853Z-0b553")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
