# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)
c("b <- board_azure(AzureStor::storage_container(", "b <-   \"https://tidymodelspipelines.blob.core.windows.net/example\"), path = \"\")")
v <- vetiver_pin_read(b, "flights_xgb", version = "20240306T183610Z-41967")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
