# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)
b <- board_connect(auth = "envvar")
v <- vetiver_pin_read(b, "emil.hvitfeldt/flights_xgb", version = "86149")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
